version: '2'
services:
  db:
    image: postgres

    container_name: cljm-db
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: cljm
      POSTGRES_PASSWORD: ${PGPASSWORD}
